/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "interface_constants.h"

namespace C {

const interfaceConstants g_interface_constants;

interfaceConstants::interfaceConstants() {
}

} // namespace

